<?php
namespace Lakshay\Converter\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-05 at 12:36:08.
 */
class DatesTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Dates
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Dates;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Lakshay\Converter\Model\Dates::setDate
     * @covers Lakshay\Converter\Model\Container::setData
     */
    public function testSetDate()
    {
        $this->assertInstanceOf('\Lakshay\Converter\Model\Dates', $this->object->setDate(new Date()));
    }
}
